### ISSUE TITLE
Вопрос про содержание страницы сегментации и классификации керна

### ISSUE THREAD

**Issue by YuliyaMilk** [DreamTeamInc/Core-frontend#14]
1. Нужно ли выводить фотографии в Ультрафиолете, и какие вообще разметки должны показываться?

**Comment by AndyS1mpson** [comment]
В каком плане выводить фотографии в УФ?
Фото уже приходит либо в УФ либо в ДС

Разметка на УФ фото содержит свечение: "Отсутствует","Насыщенное","Карбонатное"

**Comment by YuliyaMilk** [comment]
> В каком плане выводить фотографии в УФ?
> Фото уже приходит либо в УФ либо в ДС
> 
> Разметка на УФ фото содержит свечение: "Отсутствует","Насыщенное","Карбонатное"

А может ли прийти фотографии и в УС, и в ДС?

**Comment by AndyS1mpson** [comment]
может,но считайте что это 2 независимые фотографии, потому что на них разные вещи нужно сегментировать и классифицировать
